### ISSUE TITLE
How far did you get with this?

### ISSUE THREAD

**Issue by awhillas** [hamishgibbs/solid_server#1]
Hi,
I'm interested in trying to get a Solid server running on AWS Lambda functions or GCP Cloud Functions with a bucket as a storage backend. The Solid specification is largely incomprehensible to me atm but finding this repo his interesting as you seem to have a handle on it. I know it's been 3 years since you touched this. Did you end up using this?

**Comment by awhillas** [comment]
Actually, i got my head around it and now this repo makes sense to me. Is the  `get_protected` stuff still relevant ?

**Comment by hamishgibbs** [comment]
Hello, I am afraid it has been a while since I worked on this! 

I believe got bogged down at the end of the `get_protected` authentication when I began sorting out different access control for different users to the same resource. 

I am pretty sure that most of the custom token validation logic that I wrote in `get_protected` is based on standard ways of handling JSON Web Tokens and could be available (and more reliable) in another library. 

I gave up trying to implement this as I became increasingly confused with the detailed bits of the specifications -especially sections that were not fully decided. It would be great to hear how you get on!

**Comment by awhillas** [comment]
Hey, it good to see how others have gone with this specification. I too am hitting a wall with it and i haven't even started t code yet :P I'm thinking of starting simple and then trying to add the OAuth stuff on afterward so that it is easy to use some or part of the server. I guess there is an OAuth server lib for python around somewhere? I haven't even started to think about the access control stuff yet :@

The plan is to make it easy to deploy to AWS lambdas with S3 storage so that its cheap and affordable to setup and run.

Thanks for making your work public. It's been a great help to me in understanding what an implementation might look like.

p.s. having a chat about it [over on the Soild forum](https://forum.solidproject.org/t/writing-a-pod-server-from-scratch-in-python/6150/3) and your name came up.
